$(document).ready(function(){
    $(".mm1").mouseover(function(){
      $(".text1").show();
     });
     $(".mm1").mouseout(function(){
      $(".text1").hide();
     });
     $(".mm2").mouseover(function(){
      $(".text2").show();
     });
     $(".mm2").mouseout(function(){
      $(".text2").hide();
     });
     $(".mm3").mouseover(function(){
      $(".text3").show();
     });
     $(".mm3").mouseout(function(){
      $(".text3").hide();
     });
     $(".mm4").mouseover(function(){
      $(".text4").show();
     });
     $(".mm4").mouseout(function(){
      $(".text4").hide();
     });
     $(".mm5").mouseover(function(){
      $(".text5").show();
     });
     $(".mm5").mouseout(function(){
      $(".text5").hide();
     });
     $(".mm6").mouseover(function(){
      $(".text6").show();
     });
     $(".mm6").mouseout(function(){
      $(".text6").hide();
     });
     $(".mm7").mouseover(function(){
        $(".text7").show();
     });
     $(".mm7").mouseout(function(){
      $(".text7").hide();
     });
     $(".mm8").mouseover(function(){
      $(".text8").show();
     });
     $(".mm8").mouseout(function(){
      $(".text8").hide();
     });
  });